export const AuditEventType = {
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  AUTH_EMAIL_VERIFIED: 'AUTH_EMAIL_VERIFIED',
  AUTH_TOKEN_REFRESHED: 'AUTH_TOKEN_REFRESHED',

  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_ALL_REVOKED: 'SESSION_ALL_REVOKED',

  ORG_CREATED: 'ORG_CREATED',
  ORG_MEMBER_ADDED: 'ORG_MEMBER_ADDED',
  ORG_MEMBER_REMOVED: 'ORG_MEMBER_REMOVED',
  ORG_OWNERSHIP_TRANSFERRED: 'ORG_OWNERSHIP_TRANSFERRED',
  ORG_ROLE_CREATED: 'ORG_ROLE_CREATED',
  ORG_ROLE_UPDATED: 'ORG_ROLE_UPDATED',
  ORG_ROLE_DELETED: 'ORG_ROLE_DELETED',
  ORG_MEMBER_ROLE_CHANGED: 'ORG_MEMBER_ROLE_CHANGED',
} as const;

export type AuditEventType =
  (typeof AuditEventType)[keyof typeof AuditEventType];
